### ISSUE TITLE
URGENTE!! SUMO Sprint - Crowdin

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#112]
# Stringhe da tradurre
- [x] [SUMO PlayStore](https://crowdin.com/translate/sumo-playstore/936/en-it) 91 stringhe
  - [x] Da [Abbreviated...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393490) a [On Telegram...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393504) (1-15) 15 stringhe - @Sav22999
  - [x] Da [Basic Reply Format](https://crowdin.com/translate/sumo-playstore/936/en-it#1393505) a [Search Widget](https://crowdin.com/translate/sumo-playstore/936/en-it#1393519) (16-30) 15 stringhe - @joyrom
  - [x] Da [Issue Raised...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393520) a [Constant Crashes / Unreliable](https://crowdin.com/translate/sumo-playstore/936/en-it#1393534) (31-45) 15 stringhe - @joyrom
  - [x] Da ["Update: Firefox...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393535) a [Problem with new update](https://crowdin.com/translate/sumo-playstore/936/en-it#1393549) (46-60) 15 stringhe - @joyrom
  - [x] Da [How difficult...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393550) a [Not worth using”](https://crowdin.com/translate/sumo-playstore/936/en-it#1393565) (61-75) 15 stringhe - @joyrom
  - [x] Da [“Firefox I like...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393566) a [(Fine) Get more details...](https://crowdin.com/translate/sumo-playstore/936/en-it#1393581) (76-91) 16 stringhe - @joyrom

❗️  Questo progetto ha scadenza imminente (entro questa settimana)

## Informazioni sul progetto
Questo issue serve a gestire le traduzioni per lo Sprint sulla piattaforma [Crowdin](https://crowdin.com).

Chi vuole farsi avanti, a seconda della propria disponibilità, si "prenoterà" per le stringhe.
Questo per organizzare meglio l'attività di traduzione ed evitare che più persone lavorino sulle stesse stringhe.

#### Prima di iniziare:
* [Registrati](https://crowdin.com/join) sulla piattaforma di traduzione Crowdin (puoi utilizzare anche la registrazione/accesso mediante GitHub, Facebook, Twitter, GooglePlus e GitLab)
* **Leggi i capitoli della guida**, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #27 
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36

#### Prendere in carico il progetto:
* lascia un messaggio nella sezione Commenti, scrivendo di quale progetto vuoi occuparti (importante per avvisare gli altri che ci stai lavorando tu). Scrivi anche il tuo nome utente accanto al nome del progetto sulla lista qui in alto (usa l'icona della matita per modificare il testo)
* attieniti alle istruzioni del [capitolo 3](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) e del [capitolo 4](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md)
* per qualsiasi problema o domanda scrivi pure in questo issue
* quando la tua traduzione è pronta, lascia un commento nello issue per dare l'OK al QA
* rimani a disposizione per il QA, ti verrà chiesto se vuoi confermare le modifiche del revisore o meno
* e buona traduzione! 🎊 

## Link Utili
* [Web Localization Dashboard](https://l10n.mozilla-community.org/webdashboard/?locale=it) -- Lista dei progetti Pontoon con relative scadenze
* Server di test -- Per vedere dove andranno a finire le vostre traduzioni
  - per le singole pagine di [mozilla.org](https://l10n.mozilla-community.org/langchecker/?action=listpages) 
  - per [AMO](https://addons-dev.allizom.org/it/)
  - per [MDN](https://developer.allizom.org/it/)
  - per [Test Pilot](https://testpilot-l10n.dev.mozaws.net/)
  - per [Common Voice](https://voice.allizom.org/it)
  - per [Thunderbird.net](https://www.thunderbird.net/it/) *sito produzione
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

**Comment by Sav22999** [comment]
@MozillaItalia/l10n NUOVE STRINGHE URGENTI DA FARE ENTRO QUESTA SETTIMANA

**Comment by Sav22999** [comment]
Mi prendo la prima parte 1-15 stringa

**Comment by Sav22999** [comment]
Potete procedere al QA della prima parte

**Comment by joyrom** [comment]
Ok, ho tradotto tutto, si può passare al QA

**Comment by Sav22999** [comment]
Wow. Capisco l'urgenza, ma fino a sabato c'era tempo, magari qualcun'altro voleva contribuire 😂😂 ben fatto, comunque!

**Comment by Sav22999** [comment]
Complimenti a noi. Insieme alla comunità spagnola abbiamo tradotto e approvato al 100% le stringhe per primi :).

**Comment by Sav22999** [comment]
(Ho chiuso perché credo non abbia senso tenerlo aperto ancora. @kitsunenosara verifica tu)
