### ISSUE TITLE
Traduzione articoli MDN (Indice)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/Mozilla-Italia-l10n-guide#217]
# ❗ Progetto interrotto

**Attenzione**: a causa di varie esigenze di mantenimento della piattaforma MDN, è stata presa la decisione di interrompere il supporto per la localizzazione della maggior parte delle lingue, compreso l'italiano.
Gli articoli già tradotti rimarranno visualizzabili sulla piattaforma in modalità di sola lettura, ma non sarà più possibile tradurre nuovi articoli. [Ulteriori informazioni](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/).
Non ci rimane che chiudere il progetto anche su GitHub. Un enorme grazie a tutti coloro che hanno profuso il loro tempo nella localizzazione di MDN in italiano, come traduttori, revisori ed esperti interpellati. 🙇 
Data l'importanza dell'argomento, la procedura di localizzazione di ciascun articolo è stata lunga e laboriosa, per questo un grazie speciale per la vostra pazienza e costanza. È un peccato che questa iniziativa abbia avuto termine prima che potessimo trasformarci in una solida comunità, ma spero che sia stata per tutti i partecipanti un'esperienza utile e appagante. — Sara (kitsunenosaraT)

---

## Elenco articoli
- [x] [CSS layout](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout) issue #219 - Traduzione a cura di @danielebarell
- [HTML attribute: strong](https://developer.mozilla.org/it/docs/Web/HTML/Element/strong) issue #51 - Traduzione a cura di @VaiTon **INATTIVO**
- [x] [Publishing your website](https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website) issue #223 - Traduzione a cura di @dag7dev 
- [x] [HTTP](https://wiki.developer.mozilla.org/en-US/docs/Glossary/HTTP) issue #227  - Traduzione a cura di @xplosionmind 
- [x] [CSS- Building blocks](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks) issue #230 @xplosionmind 
- [x] [Introduction to CSS layout](https://developer.mozilla.org/it/docs/Learn/CSS/CSS_layout/Introduction) issue #231 @danielebarell 
- ❗ Sospeso, articolo originale in attesa di aggiornamento [Using the viewport meta tag to control layout on mobile browsers](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) issue #234 @xplosionmind 
- [x] [How to properly tag pages](https://developer.mozilla.org/it/docs/MDN/Contribute/Howto/Tag) issue #244 @kitsunenosaraT
- [x] [Normal Flow](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow) @danielebarell issue #255
- [x] [How the Web works](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works) issue #261 @JennyDC2020  
- [x] [Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) @danielebarell issue #264 
- [Creating hyperlinks](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks) @JennyDC2020 #268 **INATTIVO**

Questo è lo issue dedicato all'elencazione degli articoli MDN tradotti o in traduzione.
Se vuoi tradurre un articolo, inserisci un commento, in questo issue, del tipo:

> Vorrei tradurre l'articolo **_link_**

in questa maniera verrà creato un issue dedicato, nel quale poter discutere in maniera approfondita di quell'articolo (quindi discutere delle modifiche da fare, revisioni, ecc.).

### Prima di iniziare
- Crea un account GitHub (se non lo hai già): ti servirà sia per scrivere in questo issue, sia per accedere a MDN
- (Facoltativo) Installa i componenti aggiuntivi [Pontoon Tools](https://addons.mozilla.org/it/firefox/addon/pontoon-tools/) per ricevere le notifiche sulle stringhe mancanti in tempo reale (più altre chicche) e [MozIta L10n Addons](https://addons.mozilla.org/it/firefox/addon/mozita-l10n-addons/) per accedere più facilmente ai caratteri speciali come `’ “ ” È` ecc.
- Leggi "[Come tradurre le pagine di MDN](https://developer.mozilla.org/it/docs/MDN/Contribute/Localize/Translating_pages)"

### Leggi i capitoli della guida, se lo desideri, lascia un feedback nel relativo issue:
  - Capitolo 1 – [Buone norme di traduzione tecnica](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/1-Buone_norme_di_traduzione.md) Feedback: issue #91 
  - Capitolo 2 – [Linee guida di Mozilla Italia](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/2-Linee_guida_di_Mozilla_Italia.md) Feedback: issue #138
  - Capitolo 3 – [Flusso di lavoro](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/3-Flusso_di_lavoro.md) Feedback: issue #24 
  - Capitolo 4 – [Tipi di file](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/4-Tipi_di_file.md) Feedback: issue #31 
  - Capitolo 5  – [Risorse esterne](https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/blob/master/it/5-Risorse_esterne.md) Feedback: issue #36 

## Link Utili
* Motori di ricerca per le stringhe
  - [Pontoon: tutti i progetti](https://pontoon.mozilla.org/it/all-projects/all-resources/?utm_source=pontoon-addon&string=66616) -- Cerca simultaneamente tra tutti i progetti di Pontoon in italiano.
  - [Transvision](https://transvision.mozfr.org/) -- Motore di ricerca esterno per le stringhe Mozilla, complementare a Pontoon.
  - [Microsoft Language Portal](https://www.microsoft.com/en-us/language/Search?langID=408&Source=true&productid=0) -- Glossario Microsoft.
* [Transvision Access Key](https://transvision.mozfr.org/accesskeys/) -- Rileva eventuali errori nelle access key (da controllare ogni volta che si traduce una stringa contenente access key)
* [mozilla.dev.l10n.web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) -- Un newsgroup internazionale di riferimento per le stringhe della settimana. Condivide informazioni sui progetti correnti, anche utile per porre domande e segnalare bug ecc.

**Comment by danielebarell** [comment]
@Sav22999 Ottima panoramica! Grazie molte.
@kitsunenosaraT 

> Vorrei tradurre l'articolo, o meglio, l'intero modulo che origina da [CSS layout ](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout)
Il modulo è costituito da **13 pagine**.
Ipotizziamo che ne traduca **2 al mese**.
Il lavoro per intero verrebbe completato tra **6 mesi e mezzo**. 
Tenendo conto di un possibile delay ad Agosto, andrei in consegna intorno ad **Ottobre 2020**.
----
**Domanda**: destiniamo un issue per ogni pagina o ne facciamo uno unica?

----

**Comment by kitsunenosaraT** [comment]
@danielebarell Innanzitutto sono contenta che tu voglia prenderti tutto un modulo, penso sia più utile per chi usufruirà dei contenuti trovarsi un modulo completo piuttosto che una traduzione a macchia di leopardo di articoli a caso.

Tieni presente che non esistono scadenze per MDN. Se vuoi darti un ritmo tu, per motivarti, va benissimo, ma non sentirti sotto pressione.

Per procedere, direi che è più semplice prendere in considerazione una pagina/articolo alla volta.
Per esempio,
adesso metti il link del primo articolo che vuoi tradurre,
lo registriamo nel primo messaggio in cima allo issue
e io ti apro uno issue a parte per l'articolo.

Da quel momento puoi scrivere ogni comunicazione riguardo all'articolo nello issue dedicato e segnalare lì quando l'articolo è pronto per la revisione.
Poi ovviamente, se vediamo che non funziona bene, cambiamo metodo strada facendo.

**Comment by danielebarell** [comment]
@kitsunenosaraT 
Benissimo.
Partiamo:
> [CSS layout](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout) [1/13]

**Comment by Sav22999** [comment]
@danielebarell Perfetto. Ho creato l'issue dedicato 😄  #219

**Comment by dag7dev** [comment]
Vorrei occuparmi di tutto il capitolo "principianti": https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web

**Comment by Sav22999** [comment]
@dag7dev va bene se ti occupi dell'intero capitolo, ma per MDN abbiamo deciso di adottare traduzione di singoli articoli (così non impazziamo nelle revisioni).
Ti apro un issue dedicato a quell'articolo 😄 e buona traduzione

**Comment by Sav22999** [comment]
@dag7dev l'articolo da te scelto è stato già tradotto (ho controllato solo ora, scusa), scegliene un altro 😄

**Comment by Sav22999** [comment]
@dag7dev mi ha scritto in privato e l'articolo che ha deciso di tradurre è https://wiki.developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website

**Comment by xplosionmind** [comment]
Ciao a tutti! Ho trovato un articolo che è contrassegnato su MDN come avente priorità di localizzazione che è piuttosto breve e semplice. Mi sembra ottimo per iniziare. Mi prenoto e comincio a tradurlo!

https://wiki.developer.mozilla.org/en-US/docs/Glossary/HTTP

**Comment by kitsunenosaraT** [comment]
Ottima scelta @xplosionmind Ti ho assegnato lo issue #227 per qualsiasi comunicazione o discussione relativa all'articolo.
Buon lavoro!

**Comment by xplosionmind** [comment]
vorrei segnalare questa pagina che viene segnalata come tradotta in italiano ma l'intero contenuto è in inglese:

https://developer.mozilla.org/it/docs/MDN/Contribute/Howto/Tag

**Comment by kitsunenosaraT** [comment]
>vorrei segnalare questa pagina che viene segnalata come tradotta in italiano ma l'intero contenuto è in inglese

Grazie per la segnalazione. Si vede che qualcuno voleva tradurla e poi ha cambiato idea o non ha avuto tempo. Comunque confermo che possiamo tradurle noi 😄

**Comment by xplosionmind** [comment]
L'articolo MDN su HTTP (#227), insieme a due termini di glossario ad esso collegati, è pronto per la revisione tecnica / stilistica

**Comment by kitsunenosaraT** [comment]
Grazie per la segnalazione. Però sarebbe meglio lasciare questo issue *solo* per richiedere i nuovi articoli, altrimenti inizia a diventare difficile da seguire. È sufficiente segnalare che l'articolo è pronto nel proprio issue dedicato.

**Comment by xplosionmind** [comment]
Ciao a tutti, vorrei prenotarmi per la traduzione di [CSS building blocks](https://developer.mozilla.org/it/docs/Learn/CSS/Building_blocks).

**Comment by kitsunenosaraT** [comment]
@xplosionmind Eccoti servito: puoi continuare nello issue #230

**Comment by Sav22999** [comment]
Come richiesto da @danielebarell su Telegram, gli assegno [questo](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction) articolo, con issue #231

**Comment by danielebarell** [comment]
@Sav22999 , @kitsunenosaraT 
**Nota sull'uso di Telegram e di notifica GitHub via email**

Scusate, mi sembra di aver capito che sarebbe meglio non riempire Telegram con messaggi ridondanti.
Ho però un problema, diciamo, di gestione personale delle email.
Ovvero ne ricevo un certo quantitavo al giorno, tutte potenzialmente interessanti e meritevoli di attenzione. 
Talvolta però mi occorre concentrazione sulle cose che devo rapidamente portare avanti e quindi in certi giorni la casella email evito proprio di guardarla.
_Un po' disfunzionale come cosa, ma spero mi capiate. 🔢_ 
Per questo motivo vi chiedo di poter **proseguire su Telegram a dare (e ricevere) le notifiche base** sulla prosecuzione dei lavori che mi coinvolgono.
Per non ingolfare il canale principale dedicato a L10n vi chiedo che tali messaggi vengano notificati a/da ognuno sulla chat privata.
Siete d'accordo?

**Comment by Sav22999** [comment]
@danielebarell  Come ti ho già detto in privato, se è proprio necessario puoi utilizzare Telegram (ma non serve usare i tag). Altrimenti ti consiglio di organizzare la tua casella di posta elettronica utilizzando, ad esempio, i "Filtri" e far spostare automaticamente le notifiche di Mozilla Italia l10n in una cartella apposita.

Preferiamo utilizzare GitHub così da avere tutto pubblico e in maniera ordinata, oltre che in un unico posto.

**Comment by kitsunenosaraT** [comment]
@danielebarell 
Aggiungo a quanto già scritto da Sav22999.
Per intenderci, capisco perfettamente il tuo problema, perché anche io sono sommersa di notifiche e, giustamente, devo separare quelle lavorative o urgenti dalle altre.

In realtà è *proprio per questo* che usiamo GitHub, così anche se non vediamo o non possiamo rispondere subito alle notifiche, i messaggi rimangono in un posto dove possiamo riguardarceli con calma quando abbiamo tempo.

Ti consiglio di fare così:
- ti disiscrivi da tutti i thread di GitHub per non ricevere notifiche
- metti tra i segnalibri quei pochi issue in cui sei coinvolto attivamente (gli articoli di MDN di cui ti occupi, lo issue indice)
- ti concentri tranquillamente su quello che devi fare
- *quando decidi tu*, cioè quando hai tempo e voglia, torni sui tuoi issue e ti leggi tutti i messaggi lasciati dagli altri utenti, ti aggiorni e ci lavori sopra

- In caso io o altri avessimo bisogno di contattarti urgentemente (ma non credo che accadrà tanto spesso, dato che MDN non ha scadenze particolari), ti manderemo un messaggio su Telegram, in caso contrario attenderemo che tu risponda su GitHub con i tuoi ritmi.

Ti sembra una soluzione accettabile?

**Comment by danielebarell** [comment]
**Sav22999**
>… Altrimenti ti consiglio di organizzare la tua casella di posta elettronica utilizzando, ad esempio, i "Filtri" e far spostare automaticamente le notifiche di Mozilla Italia l10n in una cartella apposita.

**Sara**
>Ti consiglio di fare così:
…
Ti sembra una soluzione accettabile?

Senz'altro ;) 
Grazie molte per tutti i consigli 👍

**Comment by xplosionmind** [comment]
ciao, comincio la traduzione di [questo articolo](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) su MDN

**Comment by Sav22999** [comment]
@xplosionmind issue creato https://github.com/MozillaItalia/Mozilla-Italia-l10n-guide/issues/234 😄  buona traduzione

**Comment by kitsunenosaraT** [comment]
Mi prendo l'articolo [How to properly tag pages](https://developer.mozilla.org/it/docs/MDN/Contribute/Howto/Tag) issue #244 che spiega come taggare i vari articoli. In questo modo, una volta che avrò terminato, potremmo usare tutti gli stessi tag standard per facilitare la ricerca delle pagine.

**Comment by danielebarell** [comment]
Ciao a tutti!
Spero abbiate passato una buona estate.
@Sav22999 
@kitsunenosaraT 
Sono pronto a procedere con il prossimo articolo del modulo CSS Layout.

**Flusso Normale (Normal Flow)**
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow
attendo l'apertura dell'issue dedicato :)

**Comment by kitsunenosaraT** [comment]
Ciao @danielebarell ti ho appena assegnato lo issue #255 Buona traduzione!

**Comment by danielebarell** [comment]
> 
> 
> Ho visto che tutti gli articoli da tradurre presenti in questa discussione sono già stati assegnati; mi stavo chiedendo se ce ne fossero altri da tradurre, così da rendermi utile ☺️.

Ciao Jenny.
Questo thread è dedicato appunto agli articoli MDN che ciascun localizzatore si sceglie.
Quindi devi prima sceglierti l'articolo, poi fare capolino qui al #217 e segnalare che vuoi tradurlo.
Sara o Sav provvederanno ad aprirti un thread apposito ove tu potrai discutere l'avanzamento del tuo lavoro :).

**Comment by JennyDC2020** [comment]
Ciao @danielebarell 
Grazie per la precisazione. 

Ho spulciato la guida "Learn to style HTML using CSS"; partendo dalla prima sezione ("Getting started with the Web"), ho notato che l'unico articolo di cui manca la traduzione italiana è [How the Web works](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works). Potrebbe andare bene come scelta? 

Nel caso in cui ci fossero articoli con una proprità più elevata, posso sempre cambiare 😉; attendo il parere degli esperti!

**Comment by danielebarell** [comment]
> Ho spulciato la guida "Learn to style HTML using CSS"; partendo dalla prima sezione ("Getting started with the Web"), ho notato che l'unico articolo di cui manca la traduzione italiana è [How the Web works](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works). Potrebbe andare bene come scelta?

@JennyDC2020 
Ciao Jenny,
(non sono sto gran esperto ma) credo che possa andare proprio bene. 😉
Saverio (@Sav22999)  o Sara (@kitsunenosaraT) dovrebbero provvedere ad aprirti un thread apposito appena avranno il tempo di farlo.
Comunque non esitare a chiedere nel caso avessi altri dubbi.

**Comment by JennyDC2020** [comment]
@danielebarell 
Per me sei un esperto :blush:

Ok, allora attendo conferme da parte di Saverio o Sara  😉

**Comment by Sav22999** [comment]
@JennyDC2020 l'articolo da te scelto va benissimo. Ho aperto uno issue dedicato (#261), nel quale potrai discutere esattamente di quell'articolo 😄 

Buona traduzione!

**Comment by JennyDC2020** [comment]
Grazie mille @Sav22999 :star2:

**Comment by danielebarell** [comment]
Buongiorno Cari.

Prossima settimana conto di mettermi sul 5° articolo del modulo CSS Layout.
[Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox)

Rispetto al percorso che avevo stabilito potrebbe esserci una divergenza perchè l'articolo porta a una pagina di esercitazioni (Test you skills, al termine del presente articolo) , direi di localizzare anche quello.

Buon week end 
dan

**Comment by JennyDC2020** [comment]
Scrivo qui perché mi sembra il posto più adatto.

Ho notato che i seguenti articoli su MDN:

[HTML basics](https://developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/HTML_basics) 
[CSS basics](https://developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/CSS_basics) 
[JavaScript basics](https://developer.mozilla.org/it/docs/Learn/Getting_started_with_the_web/JavaScript_basics) 

hanno i titoli non tradotti. Dato che c'è una matrice comune (quel _basics_), prima di modificarli volevo chiedervi un parere; meglio:

> Basi di HTML
> Basi di CSS
> Basi di JavaScript

oppure:

> HTML: le basi
> CSS: le basi
> JavaScript: le basi

oppure ancora:

> HTML base
> CSS base 
> JavaScript base

❓

Grazie! 😊

**Comment by dag7dev** [comment]
Non so gli altri che ne pensano, a me piacciono più i primi titoli

**Comment by kitsunenosaraT** [comment]
Ottima idea uniformare i titoli, @JennyDC2020 👏 
La versione con i due punti mi piace, la trovo molto elegante.
Tuttavia, già in altri articoli non attinenti, abbiamo tradotto con "Basi di xxx", per cui sarebbe forse meglio continuare a usare questa formula.

**Comment by JennyDC2020** [comment]
Grazie per i pareri e per le dritte!
Allora, visto che anche dag7dev era d'accordo, li cambio in "Basi di xxx"

**Comment by JennyDC2020** [comment]
Buona sera a tutti!

So che kitsunenosaraT è molto occupata e non ha ancora avuto modo di vedere e correggere la traduzione dell'articolo. ❤️  Nell'attesa, ho sfogliato MDN per cercare il prossimo articolo da tradurre; nella sottocategoria _HTML — Structuring the Web_ i seguenti articoli:

- [Creating hyperlinks](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks) 
- [Advanced text formatting](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting) 
- [Document and website structure](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure)
- [Debugging HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML)
- [Assessment: Marking up a letter](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter) 
- [Assessment: Structuring a page of content](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Structuring_a_page_of_content)

non sono tradotti. Se vi va bene, mi piacerebbe iniziare dal primo (_Creating hyperlinks_) e procedere così fino all'ultimo 😊

**Comment by kitsunenosaraT** [comment]
@JennyDC2020 Mi fa piacere che tu voglia prenderti in carico questi articoli base, che sono molto necessari a chi inizia!
Ti ho assegnato lo issue dedicato #268 per Creating hyperlinks

Solo un avviso: come avevo già accennato in un altro issue, a Mozilla stanno pensando di sospendere le localizzazioni in altre lingue (ecco [l'articolo](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/) che ne parla). Per me va benissimo continuare a tradurre finché possiamo, anche perché. da quanto ho capito, gli articoli già tradotti rimarranno in modalità di sola lettura e saranno comunque utili. Però è giusto che i volontari sappiano di questo cambiamento e lo prendano in considerazione nel valutare quanto tempo ed energie dedicare a MDN.

**Comment by JennyDC2020** [comment]
Grazie per l'apertura del thread @kitsunenosaraT 

> Solo un avviso: come avevo già accennato in un altro issue, a Mozilla stanno pensando di sospendere le localizzazioni in altre lingue (ecco [l'articolo](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/) che ne parla). Per me va benissimo continuare a tradurre finché possiamo, anche perché. da quanto ho capito, gli articoli già tradotti rimarranno in modalità di sola lettura e saranno comunque utili. Però è giusto che i volontari sappiano di questo cambiamento e lo prendano in considerazione nel valutare quanto tempo ed energie dedicare a MDN.

Nooooo ma come!!!! Proprio ora che ci stavo prendendo gusto!!!  :sob: Il tempismo non è proprio il mio forte  :satisfied:
Per adesso continuo, dedicandogli il tempo che ho; appena mi direte che non ha più alcuna utilità, smetterò...

**Comment by danielebarell** [comment]
Sospendere il lavoro?
Mi trovavo bene... 
Tristezza 
😕

**Comment by kitsunenosaraT** [comment]
Buon anno a tutti!
Con l'anno nuovo arrivano notizie un po' tristi. 
Come già accennato in questa discussione e altre, i responsabili di MDN hanno deciso di interrompere il supporto per la localizzazione in varie lingue (ecco un [articolo](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/) che ne spiega i motivi). Purtroppo il momento fatidico è arrivato lo scorso dicembre e, se provate a accedere a MDN in questo momento, vi accorgerete che:
- gli articoli da voi tradotti sono sempre visibili, ma non potete più modificarli;
- non potete più creare nuove pagine per tradurre gli articoli inglesi in italiano.

Adesso, facendo il punto della situazione, rimangono quattro articoli in sospeso:

- [HTML attribute: strong](https://developer.mozilla.org/it/docs/Web/HTML/Element/strong) issue #51 - Traduzione a cura di @VaiTon Un vecchio articolo, "prenotato" che però non è mai stato tradotto, quindi lo segnalo come inattivo.
- [How the Web works](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works) issue #261 @JennyDC2020 L'articolo è stato pubblicato e adesso è consultabile in modalità di sola lettura, per questo l'ho spuntato nella lista come completo. Jenny, ti chiedo scusa per non essere riuscita a farti il QA, ma lasciati dire che hai tradotto l'articolo in modo chiaro e scorrevole. Grazie!
- [Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) @danielebarell issue #264 L'articolo è stato pubblicato e adesso è consultabile in modalità di sola lettura, per questo l'ho spuntato nella lista come completo. Daniele, vedo che ci hai messo la solita cura e scrupolosità e trovo che l'articolo vada benissimo così. Era forse l'articolo più lungo e complesso che hai tradotto finora, mi dispiace in particolar modo non avergli reso onore con un degno QA.
- [Creating hyperlinks](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks) @JennyDC2020 #268 **INATTIVO** Jenny, purtroppo questo articolo non mi appare in italiano. Spero che sia perché tu non avevi ancora iniziato la traduzione al momento della chiusura e non perché la tua traduzione parziale è stata cancellata 😟

Visto che ormai questo issue è diventato obsoleto, lo chiudo insieme agli altri issue del progetto MDN, ma sentitevi liberi di aggiungere un commento qui sotto se avete qualcosa da dire.

Un grazie immenso a tutti (senza scordare i revisori tecnici @Mte90 e @Sav22999 ) per l'impegno, la pazienza e la bravura!
